# Generated by Django 5.2.8 on 2025-11-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=100)),
                ('gaji_per_jam', models.IntegerField()),
                ('jam_kerja', models.IntegerField(default=0)),
                ('bonus_per_minuman', models.IntegerField(default=0)),
                ('miuman_terjual', models.IntegerField(default=0)),
                ('jenis', models.CharField(max_length=50)),
            ],
        ),
    ]
